### ISSUE TITLE
Conflicts with blinkid-cordova

### ISSUE THREAD

**Issue by AlibekJ** [blinkcard/blinkcard-cordova#4]
Installed blinkcard-cordova into an existing app with blinkid-cordova.
Works fine on Android, but fails to compile for iOS:

```8 duplicate symbols for architecture arm64```

Erorr logs attached:
[blinkcard.txt](https://github.com/blinkcard/blinkcard-cordova/files/6972558/blinkcard.txt)

**Comment by krizaa** [comment]
This is fixed in BlinkCard v2.6.0, you can combine the SDKs now.
