### ISSUE TITLE
HTTPS link to maven repo

### ISSUE THREAD

**Issue by ljudbane** [blinkcard/blinkcard-cordova#8]
When compiling cordova project with gradle 7+ we encountered an error about using insecure maven URLs.  Error was:

```
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'maven(http://maven.microblink.com)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.1.1/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details.
```

After checking all gradle configuration files we found that blinkcard-cordova uses an insecure link in file `BlinkCard/src/android/libBlinkCard.gradle`.

The line 
```
maven { url 'http://maven.microblink.com' }
```
should be changed to
```
maven { url 'https://maven.microblink.com' }
```

Then the build process won't fail. There's also an option to allow insecure URLs, but your repository is already hosted on https, so i think that changing the URL is the better option.

**Comment by krizaa** [comment]
Thanks for pointing this out. We fixed it in BlinkCard v2.6.0.
